version: '3'

services:
  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: welinson
      POSTGRES_PASSWORD: 135246
      POSTGRES_DB: postgres


